name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
    - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
    - name: deploy to staging
      run: |
        echo "runing from CD pipeline"
