name: CI pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        run: echo "hello i am running in ci pipeline"
