name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v4
      
    - name: test command
      uses: ./test/reuse.yaml
      # run: echo "Hello Github Actions"
